services:
  - type: web
    name: riya-mobile-shop
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: ADMIN_USER
        value: admin
      - key: ADMIN_PASS
        value: riya@123
